# Generated by Django 5.1.15 on 2026-10-02 01:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='مشروع فيديو جديد', max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('QUEUED', 'في الانتظار'), ('RENDERING', 'جاري الرندر'), ('COMPLETED', 'مكتمل'), ('FAILED', 'فشل')], default='DRAFT', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('template_name', models.CharField(default='modern_promo', max_length=100)),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('video_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
