# Generated by Django 5.1.15 on 2026-10-02 02:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='مخطط ذكاء اصطناعي جديد', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('graph_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('RUNNING', 'جاري التشغيل'), ('COMPLETED', 'مكتمل'), ('FAILED', 'فشل')], default='PENDING', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('current_node', models.CharField(blank=True, default='', max_length=100)),
                ('state_data', models.JSONField(blank=True, default=dict)),
                ('logs', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.videoproject')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='api.workflow')),
            ],
        ),
    ]
